export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_PROTUCT_BY_NAME = 'GET_PROTUCT_BY_NAME';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';

export const GET_ALL_SELLERS = 'GET_ALL_SELLERS';
export const POST_PRODUCT = 'POST_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const GET_ALL_ORDERS_OF_SELLER = 'GET_ALL_ORDERS_OF_SELLER';

export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';

export const ERRORS = 'ERRORS';
export const MESSAGE = 'MESSAGE';

export const ADMIN_UPDATE_ADD_CATEGORY = 'ADMIN_UPDATE_CATEGORY';

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_USER_HISTORY = 'GET_USER_HISTORY'
export const UPDATE_USER = 'UPDATE_USER';

export const POST_ORDER = 'POST_ORDER'

export const GET_PRODUCT_BY_SELLER_AND_CAT = 'GET_PRODUCT_BY_SELLER';

export const RESET_SLIDERS = 'RESET_SLIDERS';
export const RESET_FILTER_BY_PRICE = 'RESET_FILTER_BY_PRICE';
export const ORDER = 'ORDER';
export const ACTIVE_SELLER = 'ACTIVE_SELLER'
export const ACTIVE_CATEGORY = 'ACTIVE_CATEGORY'
export const FILTER_BY_PRICE = 'FILTER_BY_PRICE';

export const GET_PRODUCT_BY_CATEGORY = 'GET_PRODUCT_BY_CATEGORY';

export const ADD_ORDER_CAR = 'ADD_ORDER_CAR';

export const DELETE_ORDER_CAR = 'DELETE_ORDER_CAR';

export const POST_REVIEW = 'POST_REVIEW';